config/routes.rb
Books::Application.routes.draw do
  resources :books do
    collection do
      get :pdf
      post :pdf_save
      get :file_send
      get :feedback
      post :save_feedback
    end

    member do
    end
  end

  devise_for :users
  resources :users

   root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	has_attached_file :book
  validates_attachment :book, content_type: { content_type: "application/pdf" }
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
   has_attached_file :text_file
  validates_attachment_content_type :text_file, content_type: { content_type: "text/plain" }
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	has_attached_file :image,
	styles: {
	}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/rich.rb
class Rich < ActiveRecord::Base
	has_attached_file :doc
  validates_attachment_content_type :doc, :content_type => ['application/pdf']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:file_send, :save_feedback, :feedback]
  skip_before_filter :verify_authenticity_token, only: [:save_feedback]
  # GET /books
  # GET /books.json
  def index
    @books = current_user.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    respond_to do |format|
      if @book.save
        somefile = File.open(@book.book_file_name+".txt", "w")
        reader = PDF::Reader.new("public"+@book.book.url(:original,false))
          reader.pages.each do |page|
          somefile.puts(page.text)
        end
        @book.update_attribute(:text_file, somefile)
        somefile.close
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  def pdf
    @rich = Rich.new
  end

  def pdf_save
    @rich = Rich.new(rich_params)
    @rich.save
    redirect_to books_path
  end

  def file_send
    @file = Rich.last
    send_file "public"+@file.doc.url(:original,false), :type=>"application/pdf", :x_sendfile=>true 
  end

  def save_feedback
    if params[:feedback][:image].present?
      sio = StringIO.new(Base64.decode64(params[:feedback][:image]))
    else
      sio = nil
    end
    params[:feedback].delete :image
    @feedback = Feedback.new(feedback_params)
    @feedback.image = sio
    @msg = Hash.new()
    if @feedback.save
      @msg['status'] = "true"
      @msg['message'] = "Successfully Saved"
      @msg['status_code'] = "200"
    else
      @msg['status'] = "false"
      @msg['message'] = "Unsuccessfully"
      @msg['status_code'] = "300"
    end
    render json: @msg
  end

  def feedback
    @feedback = Feedback.last
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:text_file, :image, :title, :description, :book_text, :book, :user_id)
    end

    def rich_params
      params.require(:rich).permit(:doc)
    end

    def feedback_params
      params.require(:feedback).permit(:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :latitude, :longitude, :imei, :image)
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:book, :name, :email, :password, :password_confirmation, :remember_me)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :multipart => true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :required => true %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :required => true %>
  </div>

  <div class="field">
    <%= f.label :book %><br>
    <%= f.file_field :book, :required => true %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

<style>
#book_book{
  opacity:1 !important;
  position: relative;
  width:210px;
  color:black;
}

#book_image{
  opacity:1 !important;
  position: relative;
  width:210px;
  color:black;
}

label {
    float: left;
    width: 10%;
    white-space: nowrap;
    margin-top: 24px;
    padding-left: 290px;
}

.field{
  margin-right: 250px;
}
input{

}
.actions{
  margin-top: 40px;
}
</style>

app/views/books/edit.html.erb
<h4>Editing book</h4>

<%= render 'form' %>

app/views/books/feedback.html.erb
<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<div id="container2" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<div id="map-canvas" style="width:1000px; height:600px;"></div>


<div style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto" >
  <% if @feedback.image.url.present? %>
    <%= image_tag @feedback.image.url, :width => "310px", :height => "400px" %>
  <%end%>  
</div>
<script>
  $(function () {
    $('#container').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: '<%= "#{Rich.last.doc_file_name.to_s}  Feeback Report"%>'
        },
        tooltip: {
          pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Questions distribution',
            data: [
                ['Question 1',   <%= "#{@feedback.q1.to_f}"%>],
                ['Question 2',   <%= "#{@feedback.q2.to_f}"%>],
                ['Question 3',   <%= "#{@feedback.q3.to_f}"%>],
                ['Question 4',   <%= "#{@feedback.q4.to_f}"%>],
                ['Question 5',   <%= "#{@feedback.q5.to_f}"%>],
                ['Question 6',   <%= "#{@feedback.q6.to_f}"%>],
                ['Question 7',   <%= "#{@feedback.q7.to_f}"%>],
                ['Question 8',   <%= "#{@feedback.q8.to_f}"%>],
                ['Question 9',   <%= "#{@feedback.q9.to_f}"%>],
                ['Question 10',   <%= "#{@feedback.q10.to_f}"%>]
            ]
        }]
    });
});

$(function () {
        $('#container2').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: 'Question Percentage'
            },
            subtitle: {
                text: '%percentage of right answers'
            },
            xAxis: {
                categories: [
                    '<%= "#{Rich.last.doc_file_name.to_s}  Feeback Report"%>'
                ]
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Right answers (%)'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: 'Question 1',
                data: [<%= "#{@feedback.q1.to_f}"%>]
            }, {
                name: 'Question 2',
                data: [<%= "#{@feedback.q2.to_f}"%>]
    
            }, {
                name: 'Question 3',
                data: [<%= "#{@feedback.q3.to_f}"%>]
    
            }, {
                name: 'Question 4',
                data: [<%= "#{@feedback.q4.to_f}"%>]
    
            }, {
                name: 'Question 5',
                data: [<%= "#{@feedback.q5.to_f}"%>]
    
            }, {
                name: 'Question 6',
                data: [<%= "#{@feedback.q6.to_f}"%>]
    
            }, {
                name: 'Question 7',
                data: [<%= "#{@feedback.q7.to_f}"%>]
    
            }, {
                name: 'Question 8',
                data: [<%= "#{@feedback.q8.to_f}"%>]
    
            }, {
                name: 'Question 9',
                data: [<%= "#{@feedback.q9.to_f}"%>]
    
            }, {
                name: 'Question 10',
                data: [<%= "#{@feedback.q10.to_f}"%>]
    
            }]
        });
    });

var lat = <%= "#{@feedback.latitude.to_f}"%>;
var lng = <%= "#{@feedback.longitude.to_f}"%>;
if (lat != 0.0 && lng != 0.0){
var map = new google.maps.Map(document.getElementById('map-canvas'), {
      zoom: 15,
      center: new google.maps.LatLng(33.6667, 73.1667), 
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

var locations = [
      ['Visited Place', <%= "#{@feedback.latitude.to_f}"%>,<%= "#{@feedback.longitude.to_f}"%>, 3],
      ['Visited Place', <%= "#{@feedback.latitude.to_f}"%>,<%= "#{@feedback.longitude.to_f}"%>, 2],
      ['Visited Place', <%= "#{@feedback.latitude.to_f}"%>,<%= "#{@feedback.longitude.to_f}"%>, 1]
    ];
var bounds = new google.maps.LatLngBounds();
var infowindow = new google.maps.InfoWindow();    

for (i = 0; i < locations.length; i++) {  
  var marker = new google.maps.Marker({
    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
    map: map
  });

  //extend the bounds to include each marker's position
  bounds.extend(marker.position);

  google.maps.event.addListener(marker, 'click', (function(marker, i) {
    return function() {
      infowindow.setContent(locations[i][0]);
      infowindow.open(map, marker);
    }
  })(marker, i));
}

//now fit the map to the newly inclusive bounds
map.fitBounds(bounds);

//(optional) restore the zoom level after the map is done scaling
var listener = google.maps.event.addListener(map, "idle", function () {
    map.setZoom(11);
    google.maps.event.removeListener(listener);
});
}
else{

    var map;
function initialize() {
  var pin = new google.maps.LatLng(<%= "#{@feedback.latitude.to_f}"%>,<%= "#{@feedback.longitude.to_f}"%>);

  var myLatlng = new google.maps.LatLng(33.6667, 73.1667);
  var mapOptions = {
    zoom: 5,
    center: myLatlng
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);
  var marker = new google.maps.Marker({
    position: pin,
    title:"Visited Place"
  });

// To add the marker to the map, call setMap();
marker.setMap(map);

}
google.maps.event.addDomListener(window, 'load', initialize);

}

</script>

app/views/books/index.html.erb
  <%if @books.present? %>
    <h4>Listing Books</h4>
  </br></br>
  <div class="overflow">
    <table class="table table-condensed">
            <thead>
              <tr>
                <th>Image</th>
                <th>Title</th>
                <th>Description</th>
                <th>Book Name</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <%if book.image.present?%>
                    <td><%= image_tag book.image.url %></td>
                  <%else%>
                    <td><%= image_tag "missing.png",:width=>"100", :height => "100" %></td>
                  <%end%>
                  <td><%= book.title %></td>
                  <td><%= book.description %></td>
                  <td><%= book.book_file_name %></td>
                  <td colspan="2"><%= link_to 'Show', book, :class => "btn btn-primary" %>
                  <%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning" %>
                  <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%else%>
            <h4> No Item to display <h4>
          <%end%>
        </div>
<style>
.overflow{
  height:465px;
  overflow: auto;
  border: 1px solid;
}
table.table { 
  table-layout:fixed;
  overflow: hidden;
  word-wrap:break-word; 
}
img{
  height:100px;
  width:100px;
}
</style>

app/views/books/new.html.erb
<h4>Add book</h4>

<%= render 'form' %>

app/views/books/pdf.html.erb
<%= form_for @rich, :url => pdf_save_books_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :doc %>
  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

<style>
#rich_doc{
  opacity:1 !important;
  position: relative;
  width:210px;
  color:black;
}
</style>

app/views/books/show.html.erb
<p>
  <strong>Image:</strong>
  <%if @book.image.present?%>
  	<%= image_tag @book.image.url(:medium) %>
  	<%else%>
  		<%= image_tag "missing.png",:width=>"200", :height => "200" %>
  	<%end%>
</p>
</br>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
</br>
<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>
</br>
<p>
  <strong>Book Name:</strong>
  <%= @book.book_file_name %>
</p>

<style>
  img{
    height:150;
    width:150px;
    margin-left: 10px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
      <link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/bootstrap.min.css">
      <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" rel="stylesheet">
      <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="http://getbootstrap.com/2.3.2/assets/ico/favicon.png">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "highcharts.js" %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 60px 0;
      }


      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 80px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 100px;
        line-height: 1;
      }
      .jumbotron .lead {
        font-size: 24px;
        line-height: 1.25;
      }
      

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }


      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }

      .alert-info{
        color: #3a87ad;
        background-color: #d9edf7!important;
        border-color: #bce8f1;
        margin-top: -80px;
      }
      .masthead{
  margin-bottom: 35px;
  text-align: center;
}
p.muted{
  margin-left:109px;
  font-size: 10px;
  margin-top: -7px;
  font-style: italic;
}
    </style>

    <%if current_user.present?%>
    <div class="container">

      <div class="masthead">
        <h3 class="muted">Electronic-PDF</h3>
          <p class="muted">The smart reading</p>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li><a href="/books">Home</a></li>
                <li><%= link_to 'Add Book', new_book_path %></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>
      <!-- Jumbotron -->
      <div class="jumbotron">
        <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <button class="close" data-dismiss="alert">×</button> 
            <%= value %>
        </div>
      <% end %>
        <p class="lead">
          <%= yield %>
        </p>
        <!-- <a class="btn btn-large btn-success" href="./Template · Bootstrap_files/Template · Bootstrap.html">Get started today</a> -->
      </div>

      <hr>

      <!-- Example row of columns -->
      <!-- <div class="row-fluid">
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="./Template · Bootstrap_files/Template · Bootstrap.html">View details »</a></p>
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="./Template · Bootstrap_files/Template · Bootstrap.html">View details »</a></p>
       </div>
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn" href="./Template · Bootstrap_files/Template · Bootstrap.html">View details »</a></p>
        </div>
      </div> -->


      <div class="footer">
        <p>© Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

<%else%>
  <%= yield %>
<%end%>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :url => users_path, :method => "post", :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <b> attachment </b>
  <%= f.file_field :book %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>